### PR TITLE
added-unit-tests

### PR DESCRIPTION
**Pull request by manujuniris**
### Description 

This PR is created to add unit tests to the project.

The following output was captured - 

Screenshot from 2022-03-30 11-55-14

### CODE REVIEW

**Comment by samuel-uniris** [comment]
Your unit test is not in the right direction.
You have rewritten functions in your unit tests, but they should call your existing functions and assert a behavior. So your code implementation should match with the expectations provided in the tests.

Also regarding networking calls, you should use mocks to simulate the response from a server, otherwise in a automatic testing (CI) this will not work.

**Comment by manujuniris** [comment]
> Your unit test implementation is not in the right direction. You have rewritten functions in your unit tests, but they should call your existing functions and assert a behavior. So your code implementation should match with the expectations provided in the tests.
> 
> Also regarding networking calls, you should use mocks to simulate the response from a server, otherwise in a automatic testing (CI) this will not work.

ok got it

**Review by blackode — CHANGES_REQUESTED** [review]
I don't see any assertions here?    
Is this purposely written?

Something like expecting a `console.log` message with success text after deployments. or some other way that guarantees the function worked well...

I found a lib to use [test console](https://github.com/jamesshore/test-console) for expecting console messages and so...

**Comment by manujuniris** [comment]
> I don't see any assertions here? Is this purposely written?
> 
> Something like expecting a `console.log` message with success text after deployments. or some other way that guarantees the function worked well...
> 
> I found a lib to use [test console](https://github.com/jamesshore/test-console) for expecting console messages and so...

I'm getting timeout error, also
`const output = await new Promise((resolve) => {
          parser.parse("deploy-file --seed=myseed --endpoint=http://localhost:4000 --file=./aeweb.js", (err, argv, output) => {
            resolve(output);
          })

        });`

output is null here in this case

**Comment by samuel-uniris** [comment]
I suggest to leverage `nock` to mock the http calls to the archethic node. 
So you could test with scenario without a ceremony to setup infrastructure for testing.

**Pull request closed without merging**
