### PR TITLE
Handle complex website

### PR DESCRIPTION
**Pull request by Neylix**
This PR is the first implementation to solve the issue #60 

Actually the CLI do:
- Create a JSON object based on the directory tree
- Compress file content using gzip to reduce size and encode the result in base64
- Create a hosting transaction with stringified JSON object in the content
- Ask user to validate fees
- Send the transaction and show the website URL
- Indicate to the user the current step during all flow

This has been tested with actual archethic.net site and with wallet site.

But the problem is that both sites have a bigger size than the maximum content size allowed in a transaction, even after compression.
So the next step will be to reduce content of a transaction to 3.5 MB max.
We can split content in different transactions and refer the transaction address in the JSON object : 
```json
{
 "index.html":{
  "address":"000123456789"
 }
}
```
And so the node API will get the content of this file inside the transaction at "address".

But for files above 3.5 MB we need to split the file, maybe by using esbuild for example.

### CODE REVIEW

**Comment by Neylix** [comment]
Here you can find the site I used to test.
[website.zip](https://github.com/archethic-foundation/aeweb-cli/files/8772745/website.zip)
To handle over sized tx, you have to update node `git apply patch.txt`
[patch.txt](https://github.com/archethic-foundation/aeweb-cli/files/8772752/patch.txt)

**Review by manujuniris — COMMENTED** [review]
Hi @Neylix 

I tried to deploy a simple html file, but it failed.

[web.zip](https://github.com/archethic-foundation/aeweb-cli/files/8784324/web.zip)
 
Can you please also update the README file in PR?

**Comment by Neylix** [comment]
> Hi @Neylix
> 
> I tried to deploy a simple html file, but it failed.
> 
> [web.zip](https://github.com/archethic-foundation/aeweb-cli/files/8784324/web.zip)
> 
> Can you please also update the README file in PR?

Yes I'll update the Readme later. As the PR is in draft, it will surely change again.

What is the error you got ?

**Review by manujuniris — COMMENTED** [review]
Screenshot from 2022-05-30 13-35-28

**Comment by Neylix** [comment]
> Screenshot from 2022-05-30 13-35-28

Yes there is a problem with `getOriginKey` API on testnet, try with a local node

**Review by manujuniris — COMMENTED** [review]
Screenshot from 2022-05-30 14-01-28

Single File deployment failed

**Comment by manujuniris** [comment]
> > Screenshot from 2022-05-30 14-01-28
> > Single File deployment failed
> 
> It do not fail, this error is a problem in libjs. It is corrected in master but not pushed in npm version. If you go to the url you will see the file

Screenshot from 2022-05-30 14-22-03

I updated libjs, still unable to deploy single web.html file

**Comment by manujuniris** [comment]
Hello Julien 

Screenshot from 2022-05-30 16-34-15

I just checked cli is not able to convert image file path to transaction url

**Review by manujuniris — APPROVED** [review]

**Review by samuel-uniris — APPROVED** [review]

**Pull request merged**
