### PR TITLE
Adding waitConfirmations function

### PR DESCRIPTION
**Pull request by manujuniris**
Added waitConfirmations function from libjs

### CODE REVIEW

**Review by samuel-uniris — COMMENTED** [review]
I think the success message should be displayed when the transaction is confirmed and not before. Otherwise this will be a  misleading for the user.

**Comment by manujuniris** [comment]
> I think the success message should be displayed when the transaction is confirmed and not before. Otherwise this will be a misleading for the user.

fixed

**Comment by samuel-uniris** [comment]
> > I think the success message should be displayed when the transaction is confirmed and not before. Otherwise this will be a misleading for the user.
> 
> fixed

Ok but the thing if you have multiple replications, the message will be logged multiple times. 
Can be the SLA of the app to be, at least 1 replications before to write the message

**Comment by manujuniris** [comment]
> > > I think the success message should be displayed when the transaction is confirmed and not before. Otherwise this will be a misleading for the user.
> > 
> > 
> > fixed
> 
> Ok but the thing, if you have multiple replications, the message will be logged multiple times. Can be the SLA of the app to be, at least 1 replications before to write the message ?

Done

**Review by samuel-uniris — APPROVED** [review]

**Pull request merged**
